export const products = [
  {
    title: 'Scatter',
    description: 'Open-source web3 wallet',
    image: '/products/scatter/scatter-shiny.png',
    images: {
      default: '/products/scatter/scatter-shiny.png',
      hover: '/products/scatter/scatter-mobile.png',
    },
    logo: '/products/scatter/scatter-logo.png',
    bg: '/homepage/hp-scatter.png',
    status: 'past',
    slug: '/products/scatter/',
    color: '#0899FE',
    class: 'scatter',
    type: 'Product Case Study',
    size: 'large',
  },
  {
    title: 'Ultra',
    description: 'Tokenized gaming platform',
    image: '/products/ultra/build-on-ultra.png',
    images: {
      default: '/products/ultra/build-on-ultra.png',
      hover: '/products/ultra/ultra-prime-1.png',
    },
    logo: '/products/ultra/ultra-logo.svg',
    bg: '/homepage/hp-ultra.png',
    status: 'past',
    slug: '/products/ultra/',
    color: '#2E2667',
    class: 'ultra',
    type: 'Product Case Study',
    size: 'small',
  },
  {
    title: 'Doodledapp',
    description: 'No-code smart contract builder',
    image: '/products/doodledapp/doodledapp-shiny.png',
    images: {
      default: '/products/doodledapp/doodledapp-shiny.png',
      hover: '/products/doodledapp/dd-eol-app.png',
    },
    logo: '/products/doodledapp/doodledapp-logo.svg',
    bg: '/homepage/hp-doodledapp.png',
    status: 'past',
    slug: '/products/doodledapp/',
    color: '#3E74FF',
    class: 'doodledapp',
    type: 'Product Case Study',
    size: 'large',
  },
  {
    title: 'Climbing Monster',
    description: 'Training application for rock climbers',
    image: '/products/climbingmonster/climbingmonster-new.png',
    images: {
      default: '/products/climbingmonster/climbingmonster-new.png',
      hover: '/products/climbingmonster/cm-brand.png',
    },
    logo: '/products/climbingmonster/climbingmonster-logo.png',
    bg: '/homepage/hp-climbingmonster.png',
    status: 'past',
    slug: '/products/climbingmonster/',
    color: '#990000',
    class: 'climbingmonster',
    type: 'Product Case Study',
    size: 'small',
  },
  {
    title: 'Food For Future',
    description: 'Decentralized data for funding farmers',
    image: '/products/food-for-future/fff-show.png',
    images: {
      default: '/products/food-for-future/fff-show.png',
      hover: '/products/food-for-future/fff-brand.png',
    },
    logo: '/products/food-for-future/fff-logo.svg',
    bg: '/homepage/hp-fff.png',
    status: 'past',
    slug: '/products/food-for-future/',
    color: '#9446BD',
    class: 'foodforfuture',
    type: 'Product Case Study',
    size: 'small',
  },
  {
    title: 'Telos OBE',
    description: 'Open source block explorer',
    image: '/products/telos/telos-thumb.png',
    images: {
      default: '/products/telos/telos-obe-home.png',
      hover: '/products/telos/telos-show.png',
    },
    logo: '/products/telos/telos-logo.png',
    bg: '/homepage/hp-telos.png',
    status: 'past',
    slug: '/products/telos-obe/',
    color: '#571AFF',
    class: 'telos',
    type: 'Product Case Study',
    size: 'small',
  },
  {
    title: 'TouchSpin',
    description: 'iGaming on your iPad',
    image: '/products/telos/telos-thumb.png',
    images: {
      default: '/products/touchspin/image1.png',
      hover: '/products/touchspin/image2.png',
    },
    logo: '/products/touchspin/touchspin-logo.svg',
    bg: '/products/touchspin/touchspin-bg.png',
    status: 'past',
    slug: '/products/touchspin/',
    color: '#17265F',
    class: 'touchspin',
    type: 'Product Case Study',
    size: 'small',
  },
  {
    title: 'Tonara',
    description: 'Interactive sheet music',
    image: '/products/telos/telos-thumb.png',
    images: {
      default: '/products/tonara/tonara-ipad.png',
      hover: '/products/tonara/tonara-brand.png',
    },
    logo: '/products/tonara/tonara-logo.png',
    bg: '/products/tonara/tonara-bg.png',
    status: 'past',
    slug: '/products/tonara/',
    color: '#4B6FFF',
    class: 'tonara',
    type: 'Product Case Study',
    size: 'small',
  },
  {
    title: 'Qmarkets',
    description: 'Stop Wasting Time on Innovation Without Impact',
    image: '/products/telos/telos-thumb.png',
    images: {
      default: '/products/qmarkets/qm-wireframe1.png',
      hover: '/products/qmarkets/design-system.webp',
    },
    logo: '/products/qmarkets/qmarkets-logo.svg',
    bg: '/products/qmarkets/qmarkets-bg.png',
    status: 'past',
    slug: '/products/qmarkets/',
    color: '#182043',
    class: 'qmarkets',
    type: 'Product Case Study',
    size: 'small',
  },
]
