<template>
  <main id="privacy-policy" class="general-main page-top">
    <h1>Terms & Conditions of Use</h1>
    <p>This document, referred to as the "Agreement," establishes a legally binding arrangement between RAMI JAMES CONSULTING, LLC, a limited liability company registered under the laws of Delaware, USA ("Rami James Consulting"), and the user, whether an individual or representing an entity ("Client"). It pertains to the access and utilization of Rami James Consulting's website: https://www.ramijames.com (referred to as the "Website") and all associated media forms, channels, mobile websites, or mobile applications linked to or connected with it. Failure to accept and comply with the terms, conditions, and responsibilities outlined herein results in an immediate prohibition on the Client's use of the Website. The Client is hereby instructed to cease use promptly. Subsequently, the relationship between the Client and Rami James Consulting shall terminate and become void, with the exception of any outstanding obligations for services rendered, which the Client remains liable to pay to Rami James Consulting.</p>
    <h3>1. Intellectual Property Rights</h3>
    <p>Unless explicitly stated otherwise, the Website belongs to Rami James Consulting. This includes all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics of any kind, regardless of their format (referred to collectively or individually as the "Content"). Additionally, the trademarks, service marks, and logos found on the Website (referred to as the "Marks") are owned and under the control of Rami James Consulting. These assets are safeguarded by copyright and trademark laws, as well as other applicable intellectual property regulations of Delaware, foreign jurisdictions, and international agreements. The Content and Marks are provided in their current state ("As-Is") solely for your personal use and information. Unless expressly permitted in this Agreement, no portion of the Website or its Content may be copied, reproduced, aggregated, republished, uploaded, posted, displayed, encoded, translated, transmitted, distributed, sold, licensed, or exploited in any commercial manner without obtaining Rami James Consulting's explicit prior written consent. Rami James Consulting reserves all rights related to the Website, its Content, and Marks.</p>
    <h3>2. Ownership of Materials</h3>
    <p>Regardless of Rami James Consulting's ownership of Submissions, as outlined in Paragraph 6 ("Client Feedback"), all design and original source files produced on behalf of the Client ("Projects") are the exclusive property of the Client. The Client retains full copyright ownership of all Projects. In the unlikely event that legal circumstances were to ever designate Rami James Consulting as the owner, in part or whole, of a Project, the transfer of Rami James Consulting's entire interest in the Project to the Client, without any limitations, shall be irrevocable and perpetual.The Client affirms that all materials provided to Rami James Consulting, whether as examples or materials to be integrated into a project during the design process, are rightfully owned by the Client. Furthermore, the Client warrants that these materials do not infringe upon or misappropriate any third party's rights, including but not limited to intellectual property rights and rights of publicity.It's important to note that Rami James Consulting retains the ongoing right to publicly showcase the Client's design work, unless an alternative arrangement has been established as articulated in section 18 of this document. This may include sharing on social media, the website, or other digital channels.</p>
    <h3>3. Third-Party Fonts</h3>
    <p>If a Project incorporates fonts not owned by Rami James Consulting, which necessitate a commercial license for the Client to lawfully reproduce, distribute, or publicly showcase the Project ("Third-Party Font(s)"), Rami James Consulting will formally notify the Client in writing. This notification will specify that one or more Third-Party Fonts have been integrated into the Project and that the Client must obtain one or more licenses directly from the rights-holder(s) of these Third-Party Fonts in order to ensure legal reproduction, distribution, or public display of the Project. The notice will comprehensively outline the necessary licensing requirements and provide contact information for procuring the licenses.As long as Rami James Consulting has effectively communicated the inclusion of Third-Party Fonts in the manner described above, it is the Client's responsibility to manage any consequences arising from their failure to secure the requisite licenses for any Third-Party Fonts integrated into a Project.</p>
    <h3>4. User Representations</h3>
    <p>Through their use of the Website, the Client affirms and guarantees the following:</p>
    <ul>
      <li>The Client possesses the legal capacity to do so and agrees to adhere to these Terms of Use.</li>
      <li>The Client is of legal age in their jurisdiction of residence, and they are not a minor.</li>
      <li>The Client will not utilize automated or non-human methods to access the Website.</li>
      <li>The Client will refrain from employing the Website for any unlawful or unauthorized activities.</li>
      <li>The Client's utilization of the Website will not infringe upon any applicable laws or regulations.</li>
    </ul>
    <h3>5. Prohibited Activities</h3>
    <p>The Client must strictly utilize the Website solely for its intended purpose. It is prohibited to employ the Website for any commercial activities except those directly related to the services provided by Rami James Consulting on the Client's behalf. Furthermore, the Client agrees to refrain from the following actions:</p>
    <ul>
      <li>Unauthorized use of the Website.</li>
      <li>Gathering data or content with the intent of creating a database or directory.</li>
      <li>Attempting to bypass, disable, or interfere with security-related features on the Website.</li>
      <li>Unauthorized framing or linking to the Website.</li>
      <li>Deceptive or fraudulent activities aimed at Rami James Consulting or other users.</li>
      <li>Actions that disrupt or overload the Website or Rami James Consulting's networks and servers.</li>
      <li>Using the Website for competitive purposes against Rami James Consulting.</li>
      <li>Decompiling, deciphering, disassembling, or reverse engineering any part of the Website's software.</li>
      <li>Circumventing measures on the Website designed to control access.</li>
      <li>Harassing, intimidating, or threatening Rami James Consulting's employees, independent contractors, or agents.</li>
      <li>Removing copyright or other rights notices from any Content.</li>
      <li>Copying or adapting the Website's software.</li>
      <li>Uploading, transmitting, or attempting to spread viruses, Trojan horses, or other disruptive materials.</li>
      <li>Distributing material that collects or transmits information without consent.</li>
      <li>Disparaging or tarnishing Rami James Consulting's reputation.</li>
      <li>Using the Website in violation of applicable laws and regulations. The Client is expected to comply with these guidelines while using the Website.</li>
    </ul>
    <h3>6. Client Feedback</h3>
    <p>The Client acknowledges and consents to the following regarding any questions, comments, suggestions, or other feedback or submission (referred to as a "Submission"):</p>
    <ul>
      <li>Submissions shall become the exclusive property of Rami James Consulting.</li>
      <li>Rami James Consulting is not obligated to maintain the confidentiality of any Submission or take measures to ensure its confidentiality.</li>
      <li>Rami James Consulting shall possess sole and exclusive rights related to the Submission, except to the extent that rights are granted to the Client under Paragraph 2 ("Ownership of Materials").</li>
      <li>Rami James Consulting has the discretion to use and distribute a Submission for any lawful purpose, without seeking permission, acknowledgment, or compensation from the Client.</li>
      <li>The Client affirms that they have the right to make and present the Submission, and the Client hereby relinquishes all claims and recourse against Rami James Consulting for its utilization of the Submission in accordance with the terms herein and at its sole discretion thereafter.</li>
    </ul>
    <h3>7. Management</h3>
    <p>Rami James Consulting retains the authority to oversee the Website for breaches of these Terms of Use and to initiate suitable legal measures in response to violations of these Terms or any relevant laws, statutes, or regulations. Furthermore, Rami James Consulting holds the prerogative to limit or disallow access to the Website or to suspend the Client's usage of the Website.</p>
    <h3>8. Returns and Refunds</h3>
    <p>Rami James Consulting reserves the right to deny refunds based on its own self-discretion and without notice or liability to the Client. Refund requests are assessed on a case-by-case basis. Should the Client request a refund during the first month of use, all materials produced by Rami James Consulting are ownership of the company and are prohibited from being used by the Client in any way. If a refund is deemed to be appropriate, there will be a 25% fee assigned to the remaining billable period. Rami James Consulting reserves the right to take appropriate legal actions against the Client for breach of this paragraph.</p>
    <h3>9. Modification</h3>
    <p>Rami James Consulting reserves the right to change, alter, modify, amend, or remove anything or any content on the Website for any reason at its sole discretion. Rami James Consulting reserves the right to modify or discontinue all or part of the Website without notice and without liability to the Client.</p>
    <h3>10. Connection Interruptions</h3>
    <p>Rami James Consulting does not guarantee or warrant the Website will be available and accessible at all times. Issues with hardware, software, or other items may result in interruption delays or errors beyond Rami James Consulting’s control. The Client agrees that Rami James Consulting shall not be liable for any loss, damage, or inconvenience caused by the Client’s inability to access or use the Website during any interruption in the connection or service.</p>
    <h3>11. Governing Law</h3>
    <p>These Terms of Use shall be governed by and construed in accordance with the laws of Delaware without regard to conflict of law principles.</p>
    <h3>12. Disclaimer</h3>
    <p>The Website is provided on an as-is, as-available basis. The Client agrees that its use of the Website and Services is at the Client’s sole risk. Rami James Consulting disclaims all warranties, express or implied, in connection with the Website and the Client’s use thereof, including the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Rami James Consulting makes no warranties or representations about the accuracy or completeness of the Website or any content thereon or content of any websites linked to the Website and Rami James Consulting assumes no liability for any errors, mistakes, or inaccuracies of content and materials, personal injury or property damage of any nature whatsoever, any unauthorized access to or use of Rami James Consulting’s secure servers and/or any personal information and/or financial information stored therein, any interruption or cessation of transmission to or from the site, any bugs, viruses, Trojan horses, or the like which may be transmitted to or through the Website by any third party, and/or any errors or omissions in content and materials or for any loss or damage of any kind incurred as a result of the use of any content posted, transmitted, or otherwise made available through the Website. Rami James Consulting does not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party either through the Website, a hyperlinked website, or any website or mobile application featured in any advertising.</p>
    <h3>13. Limitations of Liability and Indemnification</h3>
    <p>Rami James Consulting and its directors, employees, members, independent contractors, or agents shall not be liable to the Client or any third party for any direct, indirect, consequential, incidental, special, or punitive damages, including lost profit, lost revenue, lost data, attorneys’ fees, court costs, fines, forfeitures, or other damages or losses arising from the Client’s use of the Website. The Client agrees to defend, indemnify, and hold harmless Rami James Consulting and its subsidiaries, affiliates, and all respective officers, members, agents, partners, employees, and independent contractors from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) use of the Website; (2) breach of these Terms of Use; (3) any breach of the Client’s representations and warranties set forth herein; (4) Client’s violation of the rights of any third party, including but not limited to intellectual property rights. Notwithstanding the foregoing, Rami James Consulting reserves the right, at the Client’s expense, to assume control and defense of any matter for which the Client shall be required to indemnify Rami James Consulting hereunder. The Client agrees to cooperate with the defense of such claims.</p>
    <h3>14. User Data</h3>
    <p>The Client is solely responsible for all data transmitted to or that relates to any activity the Client has undertaken using the Website. Rami James Consulting shall have no liability to the Client for any loss or corruption of any such data, and the Client hereby waives any right of action against Rami James Consulting from any such loss or corruption.</p>
    <h3>15. Electronic communications, transactions, and signatures</h3>
    <p>The Client hereby consents to receive electronic communications from Rami James Consulting, and the Client agrees that all agreements, notices, disclosures, and other communications sent via email or through the Website satisfy any legal requirement that such communication be in writing. The Client hereby agrees to the use of electronic signatures, contracts, orders, and other records, and to electronic delivery of notices, policies, and records of transactions initiated or completed by Rami James Consulting or through the Website. The Client hereby waives any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records or to payments or the granting of credits by any means other than electronic.</p>
    <h3>16. Showcasing Design Work</h3>
    <p>Rami James Consulting reserves the right to share design work on digital channels, including social media, the website, etc., unless otherwise agreed upon. The Client reserves the right to issue an NDA between themselves and Rami James Consulting, which in turn would void the right of Rami James Consulting to share or discuss the Client's work publicly.</p>
    <h3>17. Miscellaneous</h3>
    <p>These Terms of Use and any policies posted on the Website or regarding the Website constitute the entire agreement and understanding between the Client and Rami James Consulting. Failure of Rami James Consulting to enforce any right or provision of these Terms of Use shall not operate as a waiver of such right or provision. If any provision or part of these Terms of Use is determined to be unlawful, void, or unenforceable, that provision shall be severed from these Terms of Use but shall not otherwise affect the validity or unenforceability of the remaining provisions herein. Nothing in these Terms of Use, the Privacy Policy, or on the Website shall be construed to constitute the forming of a joint venture, partnership, employment, or agency relationship between the Client and Rami James Consulting.</p>
    <h3>18. Contact Information</h3>
    <p>For any questions or complaints regarding the Website, please contact Rami James Consulting at: <a href="mailto:rami@ramijames.com">rami@ramijames.com</a></p>
  </main>
</template>